# Generated by Django 2.2.19 on 2021-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210309_1513'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique score',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('recipeName', 'creator'), name='unique recipe'),
        ),
    ]
