# Generated by Django 2.2.19 on 2021-03-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210310_1313'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique score',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique recipe',
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_score'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('recipeName', 'creator'), name='unique_recipe'),
        ),
    ]
